In [1]:
# load dataset iris
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)

In [2]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [3]:
np.random.seed(0)

In [4]:
# shuffle dataset
indices = np.random.permutation(len(X)) # shuffle of index

In [5]:
indices

array([114,  62,  33, 107,   7, 100,  40,  86,  76,  71, 134,  51,  73,
        54,  63,  37,  78,  90,  45,  16, 121,  66,  24,   8, 126,  22,
        44,  97,  93,  26, 137,  84,  27, 127, 132,  59,  18,  83,  61,
        92, 112,   2, 141,  43,  10,  60, 116, 144, 119, 108,  69, 135,
        56,  80, 123, 133, 106, 146,  50, 147,  85,  30, 101,  94,  64,
        89,  91, 125,  48,  13, 111,  95,  20,  15,  52,   3, 149,  98,
         6,  68, 109,  96,  12, 102, 120, 104, 128,  46,  11, 110, 124,
        41, 148,   1, 113, 139,  42,   4, 129,  17,  38,   5,  53, 143,
       105,   0,  34,  28,  55,  75,  35,  23,  74,  31, 118,  57, 131,
        65,  32, 138,  14, 122,  19,  29, 130,  49, 136,  99,  82,  79,
       115, 145,  72,  77,  25,  81, 140, 142,  39,  58,  88,  70,  87,
        36,  21,   9, 103,  67, 117,  47])

In [6]:
# split train and test set
X_train = X[indices[:-10]] # 前140
y_train = y[indices[:-10]]
X_test = X[indices[-10:]]
y_test = y[indices[-10:]]

In [7]:
knn = KNeighborsClassifier()

In [8]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [9]:
y_pred = knn.predict(X_test)

In [10]:
y_pred

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [11]:
y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [12]:
knn.score(X_test, y_test)

0.9

In [13]:
# LR-SGD
from sklearn.linear_model import SGDClassifier

In [14]:
clf_1 = SGDClassifier(max_iter=1000)

In [15]:
clf_1.fit(X, y)

/Users/meizu/Work/py_env/my_scikit_learn/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py:183: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If max_iter is set but tol is left unset, the default value for tol in 0.19 and 0.20 will be None (which is equivalent to -infinity, so it has no effect) but will change in 0.21 to 1e-3. Specify tol to silence this warning.
  FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_iter=1000,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l2',
       power_t=0.5, random_state=None, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False)

In [16]:
X[0:3,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [17]:
clf_1.predict(X[:3, :]) 

array([0, 0, 0])

In [18]:
clf_1.score(X, y)

0.9266666666666666

In [19]:
# elastic net
from sklearn.linear_model import ElasticNet

In [20]:
clf_2 = ElasticNet(random_state=0)

In [21]:
clf_2.fit(X, y)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

In [22]:
X[0:3,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [23]:
clf_2.predict(X[:3,:])

array([0.43380935, 0.43380935, 0.40979787])

In [24]:
clf_2.score(X, y)

0.714362142129827

In [25]:
# lr-lbfgs
from sklearn.linear_model import LogisticRegression

In [26]:
clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial')

In [27]:
clf.fit(X, y)

/Users/meizu/Work/py_env/my_scikit_learn/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=0, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [28]:
X[0:3,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [29]:
clf.predict(X[:3,:])

array([0, 0, 0])

In [30]:
clf.predict_proba(X[:3, :]) 

array([[9.81802911e-01, 1.81970751e-02, 1.43580537e-08],
       [9.71729527e-01, 2.82704429e-02, 3.00353141e-08],
       [9.85452757e-01, 1.45472311e-02, 1.22691633e-08]])

In [31]:
clf.score(X, y)

0.9733333333333334

In [32]:
# naive bayes
from sklearn.naive_bayes import GaussianNB

In [33]:
nb = GaussianNB()
nb.fit(X, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [34]:
X[0:3,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [35]:
nb.predict(X[0:3,:])

array([0, 0, 0])

In [36]:
nb.score(X,y)

0.96