In [1]:
import numpy as np
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
X = [[7, 2, 3], [4, np.nan, 6], [10, 5, np.nan]]
print("X",X)
imp_mean.fit(X)
Y = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
print("Y",Y)
Z = [[np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan]]
print("Z",Z)

print("X",imp_mean.transform(X))
print("Y",imp_mean.transform(Y))
print("Z",imp_mean.transform(Z))

X [[7, 2, 3], [4, nan, 6], [10, 5, nan]]
Y [[nan, 2, 3], [4, nan, 6], [10, nan, 9]]
Z [[nan, nan, nan], [nan, nan, nan], [nan, nan, nan]]
X [[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   5.   4.5]]
Y [[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   3.5  9. ]]
Z [[7.  3.5 4.5]
 [7.  3.5 4.5]
 [7.  3.5 4.5]]


In [2]:
import numpy as np
from sklearn.impute import MissingIndicator
X1 = np.array([[np.nan, 1, 3],
               [4, 0, np.nan],
               [8, 1, 0]])
X2 = np.array([[5, 1, np.nan],
               [np.nan, 2, 3],
               [2, 4, 0]])
print("X1",X1)
print("X2",X2)

indicator = MissingIndicator()
indicator.fit(X1)

X2_tr = indicator.transform(X2)
print("X2_tr",X2_tr)

X1 [[nan  1.  3.]
 [ 4.  0. nan]
 [ 8.  1.  0.]]
X2 [[ 5.  1. nan]
 [nan  2.  3.]
 [ 2.  4.  0.]]
X2_tr [[False  True]
 [ True False]
 [False False]]
