# 科学数据处理的统计学习的教程
!'https://scikit-learn.org/stable/tutorial/statistical_inference/index.html'

## 统计学的科学 statistical learning
    - 分类数据预测函数；
    - 分类观察数据分类；
    - 无标签数据集的学习；
## phthon使用的包Python packages 
    - NumPy, 
    - SciPy, 
    - matplotlib


# 第一步 统计机器学习：
    - 数据集 datasets:两个axis
        - sample column（行）
        - featuer row(列)
     eg1:in[3]{150 samples and  4 features; signed by (n_samples, n_features)}
     eg2:in[5]{手动输入一个 digit图像数据集1798sample 8行8列}
     eg3: eg2图像数据集也可转换(reshape)成为一个8*8的长度为64的向量。
    
    - 预估器 estimators object是特征的转换器；
        - 分类器
        - 回归
        - 聚类
        - 转换器/过滤器

In [3]:
from sklearn import datasets
iris = datasets.load_iris()
data = iris.data
data.shape

(150, 4)

In [4]:
digit = datasets.load_digits()
digit.images.shape

(1797, 8, 8)

import matplotlib.pylot as plt
plt.imshow(digits.images[-1],cmap=plt.cm.gray_r)

In [0]:
# 第二 从高纬度预测输出变量：
    - 最佳临近
    - 维度


In [3]:
# 分类的iris,
# K-Nearest neighbors classifier
# 不要使用训练数据中的部分数据进行预测，应为预测的结果不会是实际上预测其他真实数据的结果；通常的做法是：将数据分为两个子集，一个进行训练，一个进行测试，以便还原预测评估器的真实预测性；
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

array([0, 1, 2])

In [5]:
# K-nearest nieghbors classifier
# split iris data in train and test data
# a random permutation, to split the data randomly
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_y_test = iris_y[indices[10:]]
# create and fit a nearest-nieghbors classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train)
knn.predict(iris_X_test)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [7]:
iris_y_test

array([2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1,
       0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2, 1, 1,
       2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 0,
       2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0, 0,
       2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2,
       0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1, 1,
       1, 0, 0, 0, 2, 1, 2, 0])